### ISSUE TITLE
mesvoisins.fr Done scraping caissedepargne: INTERNAL_ERROR

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#1967]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 5fdf88
Git sha1: 450d51
jvm_id: 63d621b9-fb5f-4987-9f42-b60b7a018692
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.140.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2019-12-17T15:09:46.389620+01:00
retriever_nice_message: Erreur interne
retriever_stack: Traceback (most recent call last):
  File "/sources/scraper/scraper.py", line 200, in scrap
    self.collect_documents(document)
  File "/sources/scraper/scraper.py", line 138, in collect_documents
    scraper.run(meta)
  File "/sources/scraper/scraperengine.py", line 317, in run
    self.close()
  File "/sources/scraper/scraperengine.py", line 264, in close
    rmtree(self.dl_dir)
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 424, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 424, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 428, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 426, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'Cache'

scraping_transaction: 6f8bfab9f87f454fb7293fd29ad02e91
external_status_code: INTERNAL_ERROR
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: false
captcha_not_solved: false
idp_not_available: false
idp_failure: true
request_user_input: false
result_is_final: true
user_info: {civilityLastnameFirstname=21 chars (ba49d4), address=60 chars (4950a0)}
external_registration_date: 2019-12-17T14:09:05.247000+00:00
external_start_date: 2019-12-17T14:09:05.579000+00:00
external_end_date: 2019-12-17T14:09:46.136000+00:00
idp_group_id: caissedepargne
scraper_id: 293520ec-9d17-41ea-8e99-5958b509553d
sharing_flow_id: 1f1e4625-5162-4f74-b84d-22c81cc3e5c0
client_id: 3dcaa635d2c2c17fcddde8c518b0f9fc
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0

**Comment by andradeje** [comment]
jp
