### ISSUE TITLE
stromio (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#1980]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: 450d51
jvm_id: b6738ead-72b1-47fc-86eb-53fccfbb4220
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 3.123.30.0
Request Path: https://app.m-itrust.com/scraping/xb/d4f849ac-0b20-4c00-89a3-b871a101b969/start
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
referer: https://app.m-itrust.com/
now: 2019-12-17T17:10:59.474495+01:00
sharing_flow_id: 254c7ef2-7688-46c4-8082-09c4deaabb29
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: stromio
scraper_id: d4f849ac-0b20-4c00-89a3-b871a101b969

**Comment by andradeje** [comment]
ok
