### ISSUE TITLE
otelo (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2091]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: 450d51
jvm_id: b6738ead-72b1-47fc-86eb-53fccfbb4220
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 88.130.57.0
Request Path: https://app.m-itrust.com/scraping/xb/3f2241d2-e0bd-4088-b9e4-29635750f1c7/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
referer: https://app.m-itrust.com/
now: 2019-12-18T14:06:54.286574+01:00
sharing_flow_id: 960f38a6-d8b8-484c-9bc4-46d62d42ba80
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: otelo
scraper_id: 3f2241d2-e0bd-4088-b9e4-29635750f1c7

**Comment by andradeje** [comment]
jp

**Comment by andradeje** [comment]
ok
