### ISSUE TITLE
nurnberger (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2391]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: 450d51
jvm_id: b6738ead-72b1-47fc-86eb-53fccfbb4220
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 87.135.207.0
Request Path: https://app.m-itrust.com/scraping/xb/e015b7f5-e708-4868-a4db-39a5bc0fd563/start
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
referer: https://app.m-itrust.com/
now: 2019-12-22T19:58:38.744795+01:00
sharing_flow_id: 8de74c99-70b5-47d4-ae00-2348bbf28828
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: nurnberger
scraper_id: e015b7f5-e708-4868-a4db-39a5bc0fd563

**Comment by andradeje** [comment]
ok
