### ISSUE TITLE
EMPTY RESULT: mesvoisins.fr Done scraping byou: COMPLETED_NOTHING_TO_DOWNLOAD

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2462]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 5fdf88
Git sha1: 450d51
jvm_id: 63d621b9-fb5f-4987-9f42-b60b7a018692
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.140.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2019-12-25T19:10:40.895518+01:00
retriever_nice_message: Aucun document disponible au téléchargement
scraping_transaction: 0a4a36e95faf49efaf65f75fda28c668
external_status_code: COMPLETED_NOTHING_TO_DOWNLOAD
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: false
captcha_not_solved: false
idp_not_available: false
idp_failure: false
request_user_input: false
result_is_final: true
user_info: {}
external_registration_date: 2019-12-25T18:09:27.159000+00:00
external_start_date: 2019-12-25T18:09:27.359000+00:00
external_end_date: 2019-12-25T18:10:40.481000+00:00
idp_group_id: byou
scraper_id: 58256b01-d51c-4744-b15f-7700367b2311$b&you
sharing_flow_id: 7bb81ca0-57d8-468f-8afd-86c5a2ad31c8
client_id: 3dcaa635d2c2c17fcddde8c518b0f9fc
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0

**Comment by andradeje** [comment]
pas de nom
