### ISSUE TITLE
gothaer_versicherungen (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2528]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: 450d51
jvm_id: b6738ead-72b1-47fc-86eb-53fccfbb4220
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 217.234.208.0
Request Path: https://app.m-itrust.com/scraping/xb/201e4e4f-2e35-405f-8346-4643556092a0/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
referer: https://app.m-itrust.com/
now: 2019-12-27T23:09:12.188679+01:00
sharing_flow_id: 8590f187-0bef-4748-9e16-78d3c70f2879
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: gothaer_versicherungen
scraper_id: 201e4e4f-2e35-405f-8346-4643556092a0

**Comment by andradeje** [comment]
ok
