### ISSUE TITLE
An EndUser joined the Improvment Program (eprimo)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2548]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 5ff09d
Git sha1: 450d51
jvm_id: 412014ff-e393-4223-8a2b-97d4ca38ad86
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 79.195.171.0
Request Path: https://app.m-itrust.com/scraping/xb/254c76d1-e255-43db-aaa4-f76367b4834b/start
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1
referer: https://app.m-itrust.com/
now: 2019-12-28T17:42:33.284272+01:00
sharing_flow_id: 901fa2d4-5fc0-447c-a4c9-3a46c329340c
client_id: 6df67293bf13afa59c1a78ab8b633ab4
idp_group_id: eprimo
scraper_id: 254c76d1-e255-43db-aaa4-f76367b4834b

**Comment by andradeje** [comment]
ok
