### ISSUE TITLE
e_wie_einfach (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2625]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: fcf0f7
jvm_id: 6c87b66f-a385-4a06-b0ea-4c1713680001
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 217.81.199.0
Request Path: https://app.m-itrust.com/scraping/xb/3eff241c-720f-46bd-9ff3-5d8a3e078c91/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
referer: https://app.m-itrust.com/
now: 2019-12-30T21:46:33.997269+01:00
sharing_flow_id: 72628e79-fee1-4273-8d26-c831aa4b66ce
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: e_wie_einfach
scraper_id: 3eff241c-720f-46bd-9ff3-5d8a3e078c91

**Comment by andradeje** [comment]
ok
