### ISSUE TITLE
allianz (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2650]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: fcf0f7
jvm_id: 6c87b66f-a385-4a06-b0ea-4c1713680001
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 217.253.62.0
Request Path: https://app.m-itrust.com/scraping/xb/d12209ab-a0ce-42f5-bc29-731b299c656f/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:71.0) Gecko/20100101 Firefox/71.0
referer: https://app.m-itrust.com/
now: 2019-12-31T10:16:15.452785+01:00
sharing_flow_id: 313ffd50-602c-486d-8be7-e829a985afee
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: allianz
scraper_id: d12209ab-a0ce-42f5-bc29-731b299c656f

**Comment by andradeje** [comment]
ok
