### ISSUE TITLE
An EndUser joined the Improvment Program (e_wie_einfach)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2656]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: fcf0f7
jvm_id: 6c87b66f-a385-4a06-b0ea-4c1713680001
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 62.143.90.0
Request Path: https://app.m-itrust.com/scraping/xb/3eff241c-720f-46bd-9ff3-5d8a3e078c91/start
User-Agent: Mozilla/5.0 (Linux; Android 9; SM-A600FN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36
referer: https://app.m-itrust.com/
now: 2019-12-31T13:41:30.394595+01:00
sharing_flow_id: b797e609-6e47-4695-ba86-2015ebffee8a
client_id: 6df67293bf13afa59c1a78ab8b633ab4
idp_group_id: e_wie_einfach
scraper_id: 3eff241c-720f-46bd-9ff3-5d8a3e078c91

**Comment by andradeje** [comment]
ok compte normalement bientôt actif
