### ISSUE TITLE
pyur (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2700]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 0bb505
Git sha1: fcf0f7
jvm_id: 32fabaad-1315-4196-bd9d-bfcd50b98865
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 95.91.251.0
Request Path: https://app.m-itrust.com/scraping/xb/eb48f144-ad7b-44fd-9d48-f710fd5bd343/start
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-01-02T12:38:38.353663+01:00
sharing_flow_id: 2fa96c20-4cdd-4c01-9cc4-c4a2b20a077b
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: pyur
scraper_id: eb48f144-ad7b-44fd-9d48-f710fd5bd343

**Comment by andradeje** [comment]
jp

**Comment by andradeje** [comment]
lf
