### ISSUE TITLE
Alte Leipziger

### ISSUE THREAD

**Issue by mimbaud** [cormoran-io/retriever-cases#2737]
Est désactivé depuis plusieurs jours.
Du coup les contributions au NDSP sont impossibles (un worker s'en est plaint).

Quel est le statut de ce scraper?
Avons-nous besoin de contributions?
Faut-il demander de l'aide à Richard?

**Comment by andradeje** [comment]
@mimbaud En effet on pourrait demander à Richard d'effectuer l'action requise sur son compte, pour voir si le scraper fonctionne après ça.

**Comment by matthieub-mitrust** [comment]
@andradeje As-tu demandé à Richard de faire le nécessaire sur son compte ? :)

**Comment by andradeje** [comment]
@matthieub-mitrust just did it now

**Comment by mimbaud** [comment]
Why is this closed? Please comment.

**Comment by andradeje** [comment]
​DP réactivé, l'action de RIchard sur son compte a bien résolu le problème @mimbaud
