### ISSUE TITLE
pyur (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2887]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 886766
Git sha1: fcf0f7
jvm_id: 6c87b66f-a385-4a06-b0ea-4c1713680001
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 141.20.213.0
Request Path: https://app.m-itrust.com/scraping/xb/eb48f144-ad7b-44fd-9d48-f710fd5bd343/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
referer: https://app.m-itrust.com/
now: 2020-01-07T11:35:42.873639+01:00
sharing_flow_id: 3a096c62-8e26-492c-bcfa-b90bd7855c0d
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: pyur
scraper_id: eb48f144-ad7b-44fd-9d48-f710fd5bd343

**Comment by andradeje** [comment]
ok
