### ISSUE TITLE
enbw (NewDataSourcesProgram_de - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2918]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 5ff09d
Git sha1: fcf0f7
jvm_id: e967b998-7572-47f8-9225-1de96c556947
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 46.5.139.0
Request Path: https://app.m-itrust.com/scraping/xb/4568dd1c-b7ca-4c29-a2ed-cdc684fa9a1f/start
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15
referer: https://app.m-itrust.com/
now: 2020-01-07T19:16:50.823273+01:00
sharing_flow_id: 69bc4dc6-b443-4701-8640-bc16b0ddad54
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: enbw
scraper_id: 4568dd1c-b7ca-4c29-a2ed-cdc684fa9a1f

**Comment by andradeje** [comment]
lf
