### ISSUE TITLE
An EndUser joined the Improvment Program (allianz)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2972]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 5ff09d
Git sha1: fcf0f7
jvm_id: e967b998-7572-47f8-9225-1de96c556947
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 109.41.1.0
Request Path: https://app.m-itrust.com/scraping/xb/d12209ab-a0ce-42f5-bc29-731b299c656f/start
User-Agent: Mozilla/5.0 (Android 7.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
referer: https://app.m-itrust.com/
now: 2020-01-08T13:52:17.679654+01:00
sharing_flow_id: 1c1647ca-3ed2-47b1-a410-64e54b654334
client_id: 6df67293bf13afa59c1a78ab8b633ab4
idp_group_id: allianz
scraper_id: d12209ab-a0ce-42f5-bc29-731b299c656f

**Comment by andradeje** [comment]
ok, compte avec sms à la connexion
