### ISSUE TITLE
numericable (NewDataSourcesProgram_fr - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3213]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 0bb505
Git sha1: fcf0f7
jvm_id: 32fabaad-1315-4196-bd9d-bfcd50b98865
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 88.125.79.0
Request Path: https://app.m-itrust.com/scraping/xb/8e272dde-1b09-460d-a879-4f511ab7f993/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
referer: https://app.m-itrust.com/
now: 2020-01-10T20:43:57.414052+01:00
sharing_flow_id: f3aa5784-0669-4329-b321-20a6ffbc1fbd
client_id: prd_MiTrust_NewDataSourcesProgram_fr
idp_group_id: numericable
scraper_id: 8e272dde-1b09-460d-a879-4f511ab7f993

**Comment by andradeje** [comment]
lf
