### ISSUE TITLE
lowi (NewDataSourcesProgram_es - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3508]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 47afd9
Git sha1: 8308c6
jvm_id: fadf6796-4dd3-4cee-96bc-84db012b96b9
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 147.83.201.0
Request Path: https://app.m-itrust.com/scraping/xb/f354010b-05f2-4cbd-acfb-aad1cc2dd8ba/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-01-14T12:03:37.806785+01:00
sharing_flow_id: d7a2d671-284d-4870-a392-5e77f20b5fca
client_id: prd_MiTrust_NewDataSourcesProgram_es
idp_group_id: lowi
scraper_id: f354010b-05f2-4cbd-acfb-aad1cc2dd8ba

**Comment by andradeje** [comment]
ok!
