### ISSUE TITLE
endesa (NewDataSourcesProgram_es - New contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3933]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 8b85d1
Git sha1: b29bd4
jvm_id: adf21a8e-a626-4bfd-b438-352e19743bb2
class_name: io.mitrust.scraping.mvc.NdspHelper
EndUser IP: 95.169.231.0
Request Path: https://app.m-itrust.com/scraping/xb/78112880-6d00-4eef-90c2-fa81529de8c3/start
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-01-19T17:32:31.068778+01:00
sharing_flow_id: f2c08ed2-509d-49d9-9018-9f7a2b545864
client_id: prd_MiTrust_NewDataSourcesProgram_es
idp_group_id: endesa
scraper_id: 78112880-6d00-4eef-90c2-fa81529de8c3

**Comment by andradeje** [comment]
jp

**Comment by andradeje** [comment]
lf
