### ISSUE TITLE
An EndUser joined the Improvment Program (congstar)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#4418]
mitrust.env: prd
spring.application.name: datasharing
Azure id: dcaf3f
Git sha1: b29bd4
jvm_id: 4a6ae4ff-2d09-4c0c-8b93-1ec8db0834ec
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 109.40.130.0
Request Path: https://app.m-itrust.com/scraping/xb/6b70fb5b-9bb6-41a1-ba1e-de92cfa1b6ec$ndsp/start
User-Agent: Mozilla/5.0 (Linux; Android 9; moto g(6) play) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-01-27T04:48:11.155071+01:00
sharing_flow_id: f3c857ae-7142-4671-b410-2f5d2abb02b7
client_id: 6df67293bf13afa59c1a78ab8b633ab4
idp_group_id: congstar
scraper_id: 6b70fb5b-9bb6-41a1-ba1e-de92cfa1b6ec$ndsp

**Comment by andradeje** [comment]
ok
