### ISSUE TITLE
otelo (NewDataSourcesProgram_de - New VALIDATED contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#4958]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 31c0e4
Git sha1: 532cc6
jvm_id: ad099f66-925d-41a2-a6c7-9dac162ad57f
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.137.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.6
now: 2020-02-02T17:25:11.713781+01:00
sharing_flow_id: 2403f9fd-aaff-4753-b390-a0cd0dbf28c5
client_id: prd_MiTrust_NewDataSourcesProgram_de
idp_group_id: otelo
scraper_id: 3f2241d2-e0bd-4088-b9e4-29635750f1c7

**Comment by andradeje** [comment]
ok
