### ISSUE TITLE
naturgy (NewDataSourcesProgram_es - New VALIDATED contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#5235]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: dcaf3f
Git sha1: 532cc6
jvm_id: 5f410306-b900-49b6-8445-fec6e34cecb3
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.138.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.6
now: 2020-02-04T18:10:46.361128+01:00
sharing_flow_id: 5b7fdd9d-35ca-4bae-8d97-6258c4916b0e
client_id: prd_MiTrust_NewDataSourcesProgram_es
idp_group_id: naturgy
scraper_id: 0cd84950-95b9-4b2e-8332-02337428a5af

**Comment by andradeje** [comment]
ok
