### ISSUE TITLE
repsol (NewDataSourcesProgram_es - New VALIDATED contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#5431]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: dcaf3f
Git sha1: 532cc6
jvm_id: 5f410306-b900-49b6-8445-fec6e34cecb3
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.138.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.6
now: 2020-02-05T21:11:58.490712+01:00
sharing_flow_id: d793bf5d-c14a-4e74-94e2-0363bd29829a
client_id: prd_MiTrust_NewDataSourcesProgram_es
idp_group_id: repsol
scraper_id: 25e6c5ee-f311-4aad-a5bf-0ebf36676a1e

**Comment by andradeje** [comment]
valide mais compte pas entièrement complété

**Comment by andradeje** [comment]
ok
