### ISSUE TITLE
An EndUser joined the Improvment Program (eon)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#5495]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 51129f
Git sha1: 532cc6
jvm_id: 162c38a1-9e68-48fe-822d-129058b65cba
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 84.174.44.0
Request Path: https://app.m-itrust.com/scraping/xb/46ac7b2c-c8de-4726-956e-722533e204e6/start
User-Agent: Mozilla/5.0 (Linux; Android 9; SM-G950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-02-06T08:13:46.776581+01:00
sharing_flow_id: be3900f6-79e8-4369-a57c-d5d2fba42e31
client_id: 6df67293bf13afa59c1a78ab8b633ab4
idp_group_id: eon
scraper_id: 46ac7b2c-c8de-4726-956e-722533e204e6

**Comment by andradeje** [comment]
login fail
