### ISSUE TITLE
An EndUser joined the Improvment Program (caissedepargne)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#6442]
mitrust.env: prd
spring.application.name: datasharing
Azure id: 31c0e4
Git sha1: 532cc6
jvm_id: d57bbf31-98e2-4cee-861c-4a740dc2d2ad
class_name: io.mitrust.scraping.mvc.WebCollectionHelper
EndUser IP: 88.120.106.0
Request Path: https://app.m-itrust.com/scraping/xb/293520ec-9d17-41ea-8e99-5958b509553d/start
User-Agent: Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Mobile Safari/537.36
referer: https://app.m-itrust.com/
now: 2020-02-12T11:20:10.454736+01:00
sharing_flow_id: e98dccfe-47e7-4be3-ba10-a2d62331d0be
client_id: 3dcaa635d2c2c17fcddde8c518b0f9fc
idp_group_id: caissedepargne
scraper_id: 293520ec-9d17-41ea-8e99-5958b509553d

**Comment by andradeje** [comment]
ok
