### ISSUE TITLE
jazztel (NewDataSourcesProgram_es - New VALIDATED contribution)

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#6444]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: dcaf3f
Git sha1: 532cc6
jvm_id: 1f6dd6e6-ec82-438f-8399-d620dd14ed34
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.137.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.6
now: 2020-02-12T11:44:19.095109+01:00
sharing_flow_id: e337adb1-1885-499a-9011-373945d1da41
client_id: prd_MiTrust_NewDataSourcesProgram_es
idp_group_id: jazztel
scraper_id: 2ddc8cb3-f162-48a7-b933-315ad7953636

**Comment by andradeje** [comment]
ok
